name: monitor-package-version
author: Justin Evans
description: Monitor changes to requirements.txt file and comment differences in Github.
branding:
    icon: "monitor"
    color: "Green"
inputs:
  upgrade:
    description: 'Monitor package upgrades?'
    required: true
    default: 'True'

  downgrade:
    description: 'Monitor package downgrades?'
    required: true
    default: 'True'

  new_package:
    description: 'Monitor when a new packages has been added?'
    required: true
    default: 'True'

  token:
    description: 'GitHub personal access token with repo access'
    required: true
    default: 'Token'

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.X

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      shell: bash

    - name: monitor-package-version
      run: |
        python src/main.py \
          --token "${{ inputs.token }}" \
          --repo "${{ github.repository }}" \
          --pull_number "${{ github.event.pull_request.number }}" \
          --commit_sha "${{ github.sha }}" \
          --existing_sha "${{ github.event.before }}" \
          --upgrade "${{ inputs.upgrade }}" \
          --downgrade "${{ inputs.downgrade }}" \
          --new_package "${{ inputs.new_package }}" \
      shell: bash
