name: monitor-package-version
author: Justin Evans
description: Monitor repository requirements and comment on commits in Github.
branding:
    icon: "monitor"
    color: "Green"
inputs:
  upgrade:
    description: 'Monitor package upgrades?'
    required: true
    default: 'True'

  downgrade:
    description: 'Monitor package downgrades?'
    required: true
    default: 'True'

  new_package:
    description: 'Monitor when a new packages has been added?'
    required: true
    default: 'True'

  token:
    description: 'GitHub personal access token with repo access'
    required: true
    default: "Token"

  repository:
    description: 'GitHub derived repository name'
    required: true
    default: ${{ github.repository }}

  existing_sha:
    description: 'GitHub derived SHA before commit'
    required: false
    default: ${{ github.event.before }}

  commit_sha:
    description: 'GitHub derived SHA on commit'
    required: false
    default: ${{ github.sha }}

  pull_number:
    description: 'Github derived pull request number'
    required: false
    default: "${{ github.event.pull_request.number }}"

  pull_request_base_sha:
    description: 'Latest commit on the base/main branch of the pull request'
    required: false
    default: "${{ github.event.pull_request.base.sha }}"

  pull_request_head_sha:
    description: 'Latest commit on the feature branch of the pull request'
    required: false
    default: "${{ github.event.pull_request.head.sha }}"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.upgrade }}
    - ${{ inputs.downgrade }}
    - ${{ inputs.new_package }}
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.existing_sha }}
    - ${{ inputs.commit_sha }}
    - ${{ inputs.pull_number }}
    - ${{ inputs.pull_request_base_sha }}
    - ${{ inputs.pull_request_head_sha }}
