name: monitor-package-version
description: User selection of package monitoring decisions.
inputs:
  upgrade:
    description: 'Monitor package upgrades?'
    required: true
    default: 'True'

  downgrade:
    description: 'Monitor package downgrades?'
    required: true
    default: 'True'

  new_package:
    description: 'Monitor when a new packages has been added?'
    required: true
    default: 'True'

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.X

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      shell: bash

    - name: Github Action
      run: |
        python src/main.py \
          --token "${{ secrets.REPO_ACCESS }}" \
          --repo "${{ github.repository }}" \
          --pull_number "${{ github.event.pull_request.number }}" \
          --commit_sha "${{ github.event.before }}" \
          --existing_sha "${{ github.event.before }}" \
          --upgrade "${{ inputs.upgrade }}" \
          --downgrade "${{ inputs.downgrade }}" \
          --new_package "${{ inputs.new_package }}" \
          --commit_number "${{ github.sha }}" \
      shell: bash