name: monitor-package-version
author: Justin Evans
description: Monitor changes to requirements.txt file and comment differences in Github.
branding:
    icon: "monitor"
    color: "Green"
inputs:
  upgrade:
    description: 'Monitor package upgrades?'
    required: true
    default: 'True'

  downgrade:
    description: 'Monitor package downgrades?'
    required: true
    default: 'True'

  new_package:
    description: 'Monitor when a new packages has been added?'
    required: true
    default: 'True'

  token:
    description: 'GitHub personal access token with repo access'
    required: true
    default: "Token"

  repository:
    description: 'GitHub derived repository name'
    required: true
    default: ${{ github.repository }}

  commit_sha:
    description: 'GitHub derived SHA on commit'
    required: true
    default: ${{ github.sha }}

  existing_sha:
    description: 'GitHub derived SHA before commit'
    required: true
    default: ${{ github.event.before }}

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.upgrade }}
    - ${{ inputs.downgrade }}
    - ${{ inputs.new_package }}
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.commit_sha }}
    - ${{ inputs.existing_sha }}
