name: Docker-Local

on:
  push:
    branches:
      - '*'

  pull_request:
        types: [opened, reopened]

jobs:
    docker_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: action.yml in root
              uses: ./ # Uses an action in the root directory
              with:
               upgrade: 'True'
               downgrade: 'True'
               new_package: 'True'
               token: "${{ secrets.REPO_ACCESS }}"
