name: Docker-Test

on:
  push:
    branches:
      - '*'

  pull_request:
        types: [opened, reopened]

jobs:
    docker_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: action.yml in root
              uses: ./ # Uses an action in the root directory
              with:
               upgrade: 'True'
               downgrade: 'True'
               new_package: 'True'
               token: "${{ secrets.REPO_ACCESS }}"
               repository: "${{ github.repository }}"
               existing_sha: "${{ github.event.before }}"
               commit_sha: "${{ github.sha }}"
               pull_number: "${{ inputs.pull_number }}"
               pull_request_base_sha: "${{ inputs.pull_request_base_sha }}"
               pull_request_head_sha: "${{ inputs.pull_request_head_sha }}"